### ISSUE TITLE
List potential risks that the application does not handle & how we can resolve them in the future.

### ISSUE THREAD

**Issue by athrael-soju** [athrael-soju/whisperChat#52]
This application is not protection ready and thus could be vulnerable to attacks. It would be good to make a list here, so that we will all be aware what vulnerabilities we would eventually need to deal with.

**Comment by danieldaugherty** [comment]
Here's a very brief list, but can expound more later if needed.
* prompt injection
* hallucination
* summarization leaving out key information or including too much
* bad user prompts
* knowledge base quality may not be very good -> GIGO
* clients would have to trust us to have their documents
CC: @Olga-Topchaya
