### ISSUE TITLE
Implement a Use case, along with prompts & templates.

### ISSUE THREAD

**Issue by athrael-soju** [athrael-soju/whisperChat#53]
For our use case we want to create:
- A summarization template, so that the AI can easily retrieve answers from the context.
- Another template to instruct the AI to respond in a certain way, or give it  a persona.
- Both templates should be in the templates.js file.

**Comment by TianrenWang** [comment]
For the prompts and templates, I would just go with a generic tone for now. Something like what's in the movie "Her". We should go with a female voice because the judges are male. I can see what I can do in terms of making the bot sound like Samantha and humanistic as possible.
