### ISSUE TITLE
Research market needs that can be solved with whisperchat

### ISSUE THREAD

**Issue by athrael-soju** [athrael-soju/whisperChat#74]

**Comment by Olga-Topchaya** [comment]
Cross-functional communication and collaboration:

- Collaborative work takes up [80%](https://hbr.org/2016/01/collaborative-overload) of the average employee’s day.
- 75% of Cross-Functional Teams Are "[Dysfunctional"](https://hbr.org/2015/06/75-of-cross-functional-teams-are-dysfunctional)
- 93% percent of companies plan to reshape their organizational structure, with most intending to flatten their organizational chart, decentralize decision making, and extend authority and control to semi-autonomous teams. [source](https://www.mercer.com/content/dam/mercer/attachments/global/webcasts/global-talent-trends-2017-europe.pdf)
- 71% of early stage companies do not provide a supportive environment for [teams to succeed ](https://www2.deloitte.com/us/en/insights/topics/strategy/cross-functional-collaboration.html)
